sudo: required
dist: trusty

git:
  submodules:
    true

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6:i386 zlib1g:i386

script:
  - make build
