sudo: required
dist: trusty

git:
  submodules:
    true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-arm-linux-gnueabi

script:
  - make CROSS_TOOLCHAIN=arm-linux-gnueabi- build
